return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    spec = {
      { "<leader>f", group = "Find/File" },
      { "<leader>g", group = "Git" },
      { "<leader>gc", desc = "Git commits" },
      { "<leader>gC", desc = "Buffer commits" },
      { "<leader>gd", desc = "Diffview open" },
      { "<leader>gD", desc = "Diffview latest commit" },
      { "<leader>gh", desc = "File history" },
      { "<leader>gl", desc = "Repository history" },
      { "<leader>gH", desc = "Repository history" },
      { "<leader>gq", desc = "Diffview close" },
      { "<leader>gs", desc = "Stage hunk" },
      { "<leader>gr", desc = "Reset hunk" },
      { "<leader>gp", desc = "Preview hunk" },
      { "<leader>gb", desc = "Blame line" },
      { "<leader>w", group = "Window" },
      { "<leader>b", group = "Buffer" },
      { "<leader>c", group = "Code/LSP" },
      { "<leader>x", group = "Diagnostics/Trouble" },
      { "<leader>d", group = "Debug (DAP)" },
      { "<leader>y", group = "Clipboard" },
      { "<leader>e", group = "Explorer" },
      { "<leader>a", group = "AI (Claude Code)" },
      { "<leader>n", group = "Notes (Review)" },
      { "<leader>o", group = "Octo (GitHub)" },
      { "<leader>op", desc = "PR list (current repo)" },
      { "<leader>or", desc = "PRs to review" },
      { "<leader>om", desc = "My PRs" },
      { "<leader>ot", desc = "Team PRs needing review" },
      { "<leader>1", group = "Go to buffer (1~9)" },
    },
  },
}
